name: CI-CD-LIVE

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@main
        with:
          repository: aspose-knowledge-base/kb-aspose
          token: ${{ secrets.REPO_TOKEN }}
          #submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --config config-live.toml --minify
        
        # Deploys built website to S3
      - name: Deploy to S3
        run: hugo --config config-live.toml deploy --maxDeletes -1 --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}

        #run: hugo --config config-qa.toml deploy --force --maxDeletes -1 --invalidateCDN
